import os
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR / "data"
JOBS_DIR = DATA_DIR / "jobs"
SESSIONS_DIR = DATA_DIR / "sessions"
PACKS_DIR = DATA_DIR / "packs"
RUNTIME_CACHE_DIR = DATA_DIR / "runtime_cache"
SCHEMAS_DIR = BASE_DIR / "app" / "schemas"

DEFAULT_GENERATOR_BACKEND = os.getenv("TABLE_GEN_DEFAULT_BACKEND", "mock")
SESSION_GENERATE_BACKEND = os.getenv("TABLE_GEN_SESSION_GENERATE_BACKEND", "comfyui")
COMFYUI_BASE_URL = os.getenv("TABLE_GEN_COMFYUI_BASE_URL", "http://localhost:8188")
COMFYUI_WORKFLOW_PATH = os.getenv("TABLE_GEN_COMFYUI_WORKFLOW_PATH", "")
COMFYUI_TIMEOUT_SECONDS = float(os.getenv("TABLE_GEN_COMFYUI_TIMEOUT_SECONDS", "30"))
COMFYUI_POLL_INTERVAL_SECONDS = float(os.getenv("TABLE_GEN_COMFYUI_POLL_INTERVAL_SECONDS", "1.0"))
COMFYUI_POLL_MAX_ATTEMPTS = int(os.getenv("TABLE_GEN_COMFYUI_POLL_MAX_ATTEMPTS", "120"))
COMFYUI_MAX_BATCH_SIZE = int(os.getenv("TABLE_GEN_COMFYUI_MAX_BATCH_SIZE", "2"))
NANO_BANANA_PRO_BASE_URL = os.getenv("TABLE_GEN_NANO_BANANA_PRO_BASE_URL", "")
NANO_BANANA_PRO_API_KEY = os.getenv("TABLE_GEN_NANO_BANANA_PRO_API_KEY", "")
NANO_BANANA_PRO_TIMEOUT_SECONDS = float(os.getenv("TABLE_GEN_NANO_BANANA_PRO_TIMEOUT_SECONDS", "90"))
NANO_BANANA_PRO_MODEL = os.getenv("TABLE_GEN_NANO_BANANA_PRO_MODEL", "gemini-3-pro-image-preview")
NANO_BANANA_PRO_ASPECT_RATIO = os.getenv("TABLE_GEN_NANO_BANANA_PRO_ASPECT_RATIO", "1:1")
NANO_BANANA_PRO_IMAGE_SIZE = os.getenv("TABLE_GEN_NANO_BANANA_PRO_IMAGE_SIZE", "2K")
STEP_GENERATE_URL = os.getenv("TABLE_GEN_STEP_GENERATE_URL", "http://step-generate:8001")
STEP_VECTORIZE_URL = os.getenv("TABLE_GEN_STEP_VECTORIZE_URL", "http://step-vectorize:8002")
STEP_SEGMENT_URL = os.getenv("TABLE_GEN_STEP_SEGMENT_URL", "http://step-segment:8004")
STEP_PALETTE_URL = os.getenv("TABLE_GEN_STEP_PALETTE_URL", "http://step-palette:8003")
STEP_HTTP_TIMEOUT_SECONDS = float(os.getenv("TABLE_GEN_STEP_HTTP_TIMEOUT_SECONDS", "420"))


def ensure_directories() -> None:
    for path in (DATA_DIR, JOBS_DIR, SESSIONS_DIR, PACKS_DIR, RUNTIME_CACHE_DIR, SCHEMAS_DIR):
        path.mkdir(parents=True, exist_ok=True)
